# Generated by Django 5.2.5 on 2025-08-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Укажите номер телефона",
                max_length=20,
                null=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
