# Generated by Django 5.2.5 on 2025-08-15 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите название товара",
                        max_length=255,
                        verbose_name="Название товара",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите цену товара",
                        verbose_name="Цена товара",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Укажите описание товара",
                        verbose_name="Описание товара",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Укажите дату создания объявления",
                        verbose_name="Дата создания объявления",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Укажите пользователя создавшего объявление",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь который создал объявление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Укажите текст отзыва",
                        verbose_name="Отзыв на товар",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Укажите дату создания отзыва",
                        verbose_name="Дата создания отзыва",
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        help_text="Укажите объявление, под которым оставлен отзыв",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="ads.ad",
                        verbose_name="Объявление, под которым оставлен отзыв",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Укажите автора отзыва",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор отзыва",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
                "ordering": ["-created_at"],
            },
        ),
    ]
